{
  "hash": "9a6a59d8f46b5f944b888312d8cd0878",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 02\"\nauthor: \"Min Htet Aung\"\ndescription: \"This is the Take-home Exercise 2\" \ndate: \"May 15, 2025\"\ndate-modified: \"last-modified\"\nformat: \n  docx:\n    prefer-html: true\neditor: visual\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1. Overview\n\nThis case from the [***VAST Challenge 2025 Mini-Challenge 1***](https://vast-challenge.github.io/2025/MC1.html) looks at the growth of Sailor Shift, a global music legend who began her career in the Oceanus Folk genre. Sailor has been essential in bringing Oceanus Folk to a global audience since her early days with the band Ivy Echoes and her 2028 viral breakthrough. Her frequent solo releases, cross-genre partnerships, and encouragement of emerging artists have increased the genre's visibility and brought the island nation of Oceanus to the notice of the world.\n\n## 1.1. The Task\n\nThe task is to analyze a knowledge graph of artists, songs, albums, and influences to uncover insights about Sailor Shift’s career, the evolution of Oceanus Folk, and the genre’s broader impact. This includes identifying the traits of rising stars, visualizing the career paths of three artists for comparison, and predicting the next wave of Oceanus Folk talent over the next five years.\n\n## 1.2. Loading Packages\n\n| Packages | Purpose |\n|--------------------|----------------------------------------------------|\n| `tidyverse` | Core data manipulation and visualization tools (`dplyr`, `ggplot2`, `tibble`, etc.). |\n| `jsonlite` | Reads the JSON file into a structured R format for further processing. |\n| `SmartEDA` | Automates exploratory data analysis (EDA), summaries, and profiling. |\n| `tidygraph` | Enables graph/network operations using tidy data principles. |\n| `ggraph` | Visualization extension for `tidygraph`, helps draw static network diagrams with `ggplot2`. |\n| `igraph` | Low-level graph manipulation and analysis (e.g., neighbors, components, layout). |\n| `lubridate` | Easy handling and manipulation of date/time data. |\n| `janitor` | Cleans messy column names and tabular data efficiently. |\n| `ggthemes` | Offers extra themes and styles for `ggplot2` visualizations. |\n| `plotly` | Creates interactive plots from `ggplot2` (like tooltips in heatmaps and PCA plots). |\n| `DT` | Creates interactive HTML data tables for viewing in RMarkdown or Shiny. |\n| `ggfortify` | Helps plot PCA and clustering results directly from `prcomp` and `kmeans`. |\n| `visNetwork` | Builds interactive network graphs (like EGO networks) in HTML widgets. |\n| `factoextra` | Enhances visualization and interpretation of multivariate results (PCA, clustering). |\n| `FactoMineR` | Performs multivariate analysis like PCA, MCA, CA—underlying support for `factoextra`. |\n| `fmsb` | Creates radar/spider charts—used to compare rising star profiles visually. |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, jsonlite, SmartEDA, tidygraph, ggraph, igraph, lubridate, janitor, ggthemes, plotly, DT, ggfortify, visNetwork, factoextra, FactoMineR, fmsb)\n```\n:::\n\n\n\n## 1.3. Reading jason file\n\nThis step reads the knowledge graph data from the JSON file (`MC1_graph.json`) into R as a structured list object for further processing.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkg <- fromJSON(\"data/MC1_graph.json\")\n```\n:::\n\n\n\n## 1.4. Inspect structure\n\nThis step inspects the high-level structure of the imported JSON object, revealing it contains metadata (`directed`, `multigraph`), graph-level details, and two main components: a ***nodes table with 17,412 entries*** and a ***links (edges) table with 37,857 connections**.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(kg,max.level = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     :List of 2\n $ nodes     :'data.frame':\t17412 obs. of  10 variables:\n $ links     :'data.frame':\t37857 obs. of  4 variables:\n```\n\n\n:::\n:::\n\n\n\n# 2. Initial Data Cleaning and Wrangling\n\nThis section converts the JSON data into tidy data frames for nodes and edges, cleans column names, inspects the data structure, and ensures that date fields (like release dates) are properly formatted for analysis.\n\n## 2.1. Convert JSON to DataFrames\n\nThis step extracts the `nodes` and `links` components from the ***JSON object*** and converts them into separate tibble data frames (`nodes_tbl` and `edges_tbl`) for easier manipulation and analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- as_tibble(kg$nodes)\nedges_tbl <- as_tibble(kg$links)\n```\n:::\n\n\n\n## 2.2. Explore and Clean the Data\n\nThis step provides an overview of the structure and contents of the nodes and edges data frames, showing that the dataset includes ***17,412 nodes*** (e.g., songs, people, albums) with attributes like genre and release date, and ***37,857 edges*** representing various relationships such as collaborations or influences.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(nodes_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17,412\nColumns: 10\n$ `Node Type`    <chr> \"Song\", \"Person\", \"Person\", \"Person\", \"RecordLabel\", \"S…\n$ name           <chr> \"Breaking These Chains\", \"Carlos Duffy\", \"Min Qin\", \"Xi…\n$ single         <lgl> TRUE, NA, NA, NA, NA, FALSE, NA, NA, NA, NA, TRUE, NA, …\n$ release_date   <chr> \"2017\", NA, NA, NA, NA, \"2026\", NA, NA, NA, NA, \"2020\",…\n$ genre          <chr> \"Oceanus Folk\", NA, NA, NA, NA, \"Lo-Fi Electronica\", NA…\n$ notable        <lgl> TRUE, NA, NA, NA, NA, TRUE, NA, NA, NA, NA, TRUE, NA, N…\n$ id             <int> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1…\n$ written_date   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"2020\", NA, NA,…\n$ stage_name     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ notoriety_date <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(edges_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 37,857\nColumns: 4\n$ `Edge Type` <chr> \"InterpolatesFrom\", \"RecordedBy\", \"PerformerOf\", \"Composer…\n$ source      <int> 0, 0, 1, 1, 2, 2, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5…\n$ target      <int> 1841, 4, 0, 16180, 0, 16180, 0, 5088, 14332, 11677, 2479, …\n$ key         <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n\n## 2.3. Clean and Inspect\n\nThis step standardizes the column names in both the nodes and edges tables using `clean_names()` to ensure consistent, analysis-friendly formatting for downstream processing.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- clean_names(nodes_tbl)\nedges_tbl <- clean_names(edges_tbl)\n```\n:::\n\n\n\n## 2.4. Convert Dates\n\nThis step converts the `release_date` column in the nodes table from character to integer format, allowing for proper chronological analysis and visualization.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- nodes_tbl %>%\n  mutate(release_date = as.integer(release_date))\n```\n:::\n\n\n\n# 3. Initial EDA\n\nThis section conducts initial exploratory data analysis (EDA) to understand the structure and distribution of the dataset, including the types and frequencies of nodes and edges, genre trends over time, and the presence of notable songs.\n\n## 3.1. Count of Edge Types\n\nThis bar chart visualizes the frequency of different edge types in the music knowledge graph, representing the types of relationships between entities (e.g., people, songs, albums). The most common connection is `PerformerOf` with ***13,587*** instances, followed by `ComposerOf`, `LyricistOf`, and `RecordedBy`, highlighting the dominant role of performance and creation-related links in the dataset. Less frequent edge types like `MemberOf` and `DirectlySamples` suggest fewer band affiliations or sampling relationships, reflecting how musical influence is more often conveyed through performance and composition.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = edges_tbl, aes(y = edge_type)) +\n  geom_bar() +\n  geom_text(stat = 'count', aes(label = ..count..), \n            hjust = -0.2, color = \"black\", size = 2) +  # Data labels\n  labs(title = \"Distribution of Edge Types\",       # Main title\n       subtitle = \"Count of different connection types\",  # Subtitle\n       y = \"Edge Type\",                           # Y-axis label\n       x = \"Count\") +                             # X-axis label\n  theme_minimal() +                               # Clean theme\n  theme(plot.title = element_text(size = 14, face = \"bold\"),  # Title formatting\n        axis.text.y = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-8-1.png)\n:::\n:::\n\n\n\n## 3.2. Count of Node Types\n\nThis bar chart illustrates the distribution of different node types in the music knowledge graph. The most prevalent node type is `Person` ***(11,136 entries)***, indicating a strong focus on individual artists, followed by `Song` and `RecordLabel`. Fewer entries for `Album` and `MusicalGroup` suggest that the dataset emphasizes people and their direct musical contributions over collective entities or album-level data. This breakdown helps frame the scope of the dataset and its emphasis on artist-level relationships.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = nodes_tbl, aes(y = node_type)) +\n  geom_bar() +\n  geom_text(stat = 'count', aes(label = ..count..), \n            hjust = -0.2, color = \"black\", size = 2.5) +  # Data labels\n  labs(title = \"Distribution of Node Types\",       # Main title\n       subtitle = \"Count of different node categories\",  # Subtitle\n       y = \"Edge Type\",                           # Y-axis label\n       x = \"Count\") +                             # X-axis label\n  theme_minimal() +                               # Clean theme\n  theme(plot.title = element_text(size = 14, face = \"bold\"),  # Title formatting\n        axis.text.y = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-9-1.png)\n:::\n:::\n\n\n\n## 3.3. Popularity over Time (by Genre)\n\nThis heatmap visualizes the number of song releases over time by genre, capturing the evolution and relative activity across musical styles. Each cell represents the number of songs released in a given year for a specific genre, with darker shades indicating higher counts. The visualization helps identify trends, bursts of activity, and the emergence of genres over decades.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmap_data <- nodes_tbl %>%\n  filter(node_type == \"Song\", !is.na(release_date)) %>%\n  count(genre, release_date) %>%\n  ungroup() %>%\n  na.omit()\n\n# Create ggplot heatmap\np <- ggplot(heatmap_data, \n            aes(x = release_date, \n                y = fct_rev(fct_infreq(genre)), \n                fill = n,\n                text = paste0(\"Genre: \", genre, \n                              \"<br>Release Date: \", release_date, \n                              \"<br>Number of Songs: \", n))) +\n  geom_tile(color = \"white\", size = 0.1) +\n  theme_tufte(base_family = \"Helvetica\") +\n  coord_equal() +\n  scale_fill_gradient(name = \"# of songs\",\n                      low = \"sky blue\", \n                      high = \"dark blue\") +\n  labs(x = NULL, y = NULL, title = \"Song Releases Over Time by Genre\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 4, size = 8),\n        axis.text.y = element_text(size = 6),\n        axis.ticks = element_blank(),\n        plot.title = element_text(hjust = 0.5),\n        legend.title = element_text(size = 8),\n        legend.text = element_text(size = 6))\n\n# Convert to interactive plot\nggplotly(p, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-10-1.png)\n:::\n:::\n\n\n\n::: callout-tip\n### Insights\n\n-   Oceanus Folk shows consistent and increasing activity, especially after 2020, aligning with Sailor Shift’s rise.\n-   Indie Pop and Indie Folk have maintained strong, steady growth, becoming dominant post-2010.\n-   Genres like Dream Pop and Synthwave also show rising popularity after 2015, reflecting global music trends.\n-   Post-2020 shows a broader diversification across niche genres, suggesting increased genre blending and experimentation.\n:::\n\n## 3.4. Notable Songs and Their Genres\n\nThis horizontal bar chart displays the number of notable songs categorized by genre, providing insight into which musical styles have had the most significant impact or recognition. The count is derived from songs marked as notable in the dataset, highlighting genres that have produced widely recognized or influential works.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl %>%\n  filter(notable == TRUE & node_type == \"Song\") %>%\n  count(genre, sort = TRUE) %>%\n  ggplot(aes(x = reorder(genre, n), y = n)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  geom_text(aes(label = n), hjust = -0.1, size = 2.5) +  # Data labels\n  coord_flip() +\n  labs(\n    title = \"Count of Notable Songs by Genre\",\n    x = \"Genre\",\n    y = \"Number of Notable Songs\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    axis.title = element_text(size = 12)\n  ) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))  # Add space for labels\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-11-1.png)\n:::\n:::\n\n\n\n::: callout-tip\n### Insights\n\n-   Dream Pop leads with 563 notable songs, indicating strong critical or cultural influence.\n-   Indie Folk and Synthwave also have high numbers, showing their sustained popularity.\n-   Oceanus Folk has 179 notable songs, signaling its substantial and growing relevance.\n:::\n\n# 4. Network Analysis and Visualization\n\nThis section constructs and explores the music knowledge graph by mapping relationships between artists, songs, albums, and genres. It transforms the cleaned data into a graph structure using node and edge indices, enabling detailed network analysis. These visualizations help reveal collaboration patterns, influence pathways, and the structural role of key artists—particularly in tracing the spread and evolution of Oceanus Folk.\n\n## 4.1. Create Graph Object\n\nThis step prepares the data for network analysis by constructing a directed graph object. It begins by mapping node IDs to row indices, then remaps the source and target columns in the edges to match these indices. After filtering out incomplete connections, the cleaned nodes and edges are used to build a `tbl_graph` object, enabling efficient graph operations and visualizations using the `tidygraph` framework.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Create a mapping from node `id` to row index\nid_map <- tibble(id = nodes_tbl$id,\n                 index = seq_len(nrow(nodes_tbl)))\n\n# Step 2: Map `source` and `target` in edges to the correct row index\nedges_tbl_mapped <- edges_tbl %>%\n  left_join(id_map, by = c(\"source\" = \"id\")) %>%\n  rename(from = index) %>%\n  left_join(id_map, by = c(\"target\" = \"id\")) %>%\n  rename(to = index)\n\n# Step 3: Remove any edges with missing mapped values\nedges_tbl_clean <- edges_tbl_mapped %>%\n  filter(!is.na(from), !is.na(to)) %>%\n  mutate(from = as.integer(from),\n         to = as.integer(to))\n\n# Step 4: Ensure the node table is clean\nnodes_tbl_clean <- nodes_tbl %>%\n  mutate(id = as.integer(id)) %>%\n  distinct()\n\n# Step 5: Create the graph object\ngraph <- tbl_graph(nodes = nodes_tbl_clean, edges = edges_tbl_clean, directed = TRUE)\n```\n:::\n\n\n\n## 4.2. Rising Star Profile\n\nThis step builds a structured profile for each artist in the graph to identify and compare rising stars in the music industry. It starts by extracting metadata on songs, albums, and people, then maps contribution edges (e.g., PerformerOf, ComposerOf) to link artists to their works. The code calculates key metrics per artist — such as total number of works, notable songs, Oceanus Folk contributions, debut year, and time to achieve notability. It also counts collaborations based on influence-related edges (e.g., CoverOf, InterpolatesFrom).\n\nFinally, all these attributes are combined into a unified `rising_star_profile` table, which is displayed interactively. This profile helps quantify artistic impact and growth trajectory — laying the foundation for identifying standout talent and predicting future Oceanus Folk stars.\n\n::: callout-note\n### Puropse\n\n-   To quantify artist trajectories using measurable criteria.\n-   To identify fast-rising, influential artists based on productivity, genre focus, and collaboration.\n-   To support comparative and predictive analysis in later steps of the challenge.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Extract song/album and person metadata\nsongs_albums <- nodes_tbl_clean %>%\n  filter(node_type %in% c(\"Song\", \"Album\")) %>%\n  select(work_id = id, release_date, genre, notable)\n\npeople <- nodes_tbl_clean %>%\n  filter(node_type == \"Person\") %>%\n  distinct(id, .keep_all = TRUE) %>%\n  select(person_id = id, name)\n\n# Step 2: Edge types\ncontribution_types <- c(\"ComposerOf\", \"PerformerOf\", \"ProducerOf\", \"LyricistOf\", \"RecordedBy\")\ncollab_types <- c(\"LyricalReferenceTo\", \"CoverOf\", \"InterpolatesFrom\", \"DirectlySamples\")\n\n# Step 3: Map contribution edges (index → actual IDs)\ncreated_links <- edges_tbl_clean %>%\n  filter(edge_type %in% contribution_types) %>%\n  left_join(id_map, by = c(\"from\" = \"index\")) %>%\n  rename(person_id = id) %>%\n  left_join(id_map, by = c(\"to\" = \"index\")) %>%\n  rename(work_id = id)\n\n# Step 4: Join to valid song/album metadata\nartist_works <- created_links %>%\n  left_join(songs_albums, by = \"work_id\") %>%\n  filter(!is.na(release_date))  # exclude dangling works\n\n# Step 5: Compute profile metrics\nrising_star_profile <- artist_works %>%\n  group_by(person_id) %>%\n  summarise(\n    total_works = n(),\n    notable_works = sum(notable, na.rm = TRUE),\n    oceanus_folk_works = sum(genre == \"Oceanus Folk\", na.rm = TRUE),\n    first_release = min(as.integer(release_date), na.rm = TRUE),\n    first_notable = if (any(notable == TRUE)) {\n      min(as.integer(release_date[notable == TRUE]), na.rm = TRUE)\n    } else {\n      NA_integer_\n    },\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    time_to_notability = ifelse(!is.na(first_notable),\n                                first_notable - first_release, NA)\n  )\n\n# Step 6: Collaboration links mapped\ncollaborations <- edges_tbl_clean %>%\n  filter(edge_type %in% collab_types) %>%\n  count(from, name = \"collaborations\") %>%\n  left_join(id_map, by = c(\"from\" = \"index\")) %>%\n  rename(person_id = id)\n\n# Step 7: Add collaborations to profile\nrising_star_profile <- rising_star_profile %>%\n  left_join(collaborations, by = \"person_id\") %>%\n  mutate(collaborations = replace_na(collaborations, 0))\n\n# Step 8: Final join ONLY with real people\nrising_star_profile <- rising_star_profile %>%\n  inner_join(people, by = \"person_id\") %>%  # ensures node_type == \"Person\"\n  relocate(person_id, name)\n\n# Display the rising star profile\ndatatable(\n  rising_star_profile,\n  rownames = FALSE,\n  options = list(\n    pageLength = 10,\n    autoWidth = TRUE,\n    scrollX = TRUE\n  ),\n  caption = htmltools::tags$caption(\n    style = 'caption-side: top; text-align: left; font-size: 16px; font-weight: bold;',\n    'Table: ', 'Rising Star Profile of Artists'\n  )\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-13-1.png)\n:::\n:::\n\n\n\n## 4.3. Clustering and PCA for the Rising Star Profiles\n\nThis step uses ***Principal Component Analysis (PCA)*** and ***K-means clustering*** to group artists based on their profile metrics: ***total works, notable works, Oceanus Folk contributions, collaborations, and time to notability***. The PCA reduces these features to two dimensions (PC1 and PC2) for visualization, while K-means divides the artists into 3 clusters to reveal distinct patterns of career progression and influence.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Prepare data\nclustering_data <- rising_star_profile %>%\n  select(person_id, name, total_works, notable_works, oceanus_folk_works, collaborations, time_to_notability) %>%\n  drop_na()\n\n# Step 2: Scale numeric features only\nscaled_data <- clustering_data %>%\n  select(-person_id, -name) %>%\n  scale()\n\n# Step 3: K-means clustering\nset.seed(123)\nkmeans_result <- kmeans(scaled_data, centers = 3, nstart = 25)\n\n# Step 4: PCA (first 2 components only)\npca_result <- prcomp(scaled_data)\npca_df <- as.data.frame(pca_result$x[, 1:2]) %>%\n  mutate(cluster = factor(kmeans_result$cluster),\n         name = clustering_data$name)\n\n# Step 5: Simplified plotly config (prevent overload)\nlibrary(plotly)\n\n# Set viewer to browser (avoids slow Viewer pane rendering)\noptions(viewer = NULL)\n\n# Create plot with shorter tooltips\np <- ggplot(pca_df, aes(x = PC1, y = PC2, color = cluster,\n                        text = paste0(\"Artist: \", name))) +\n  geom_point(size = 2.5, alpha = 0.7) +\n  labs(title = \"PCA Clustering of Rising Artists\") +\n  theme_minimal()\n\n# Render in browser\nggplotly(p, tooltip = \"text\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-14-1.png)\n:::\n:::\n\n\n\n::: callout-tip\n### Clustering Explanation:\n\n-   ***Cluster 1 (Red):*** Average or below-average artists with limited impact — likely early in their careers.\n-   ***Cluster 2 (Green):*** Balanced artists with steady progress and moderate recognition.\n-   ***Cluster 3 (Blue):*** Outliers or standout artists with high productivity or rapid rise — strong candidates for future stars.\n:::\n\n## 4.4. Influence Network for Oceanus Folk Gener\n\nThis step constructs an interactive ***influence network*** focused on contributors to notable Oceanus Folk albums. It identifies artists who composed, performed, or produced such albums and maps their direct connections to albums and other collaborators using a 1-hop ego network.\n\nThe network shows ***“Person” nodes in blue*** and ***“Album” nodes in yellow***, enabling exploration of how artists are interconnected through their work in the Oceanus Folk genre.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Find Oceanus Folk albums that are notable\noceanus_folk_album_ids <- nodes_tbl_clean %>%\n  filter(genre == \"Oceanus Folk\", node_type == \"Album\", notable == TRUE) %>%\n  pull(id)\n\n# Step 2: Define contribution edges and map to IDs\ncontribution_types <- c(\"ComposerOf\", \"PerformerOf\", \"ProducerOf\", \"LyricistOf\", \"RecordedBy\")\nid_map <- tibble(index = 1:nrow(nodes_tbl_clean), id = nodes_tbl_clean$id)\n\n# Step 3: Get edges where people contributed to those albums\noceanus_contributions <- edges_tbl_clean %>%\n  filter(edge_type %in% contribution_types) %>%\n  left_join(id_map, by = c(\"to\" = \"index\")) %>%\n  rename(to_id = id) %>%\n  filter(to_id %in% oceanus_folk_album_ids)\n\n# Step 4: Get contributing artists\noceanus_artist_indices <- unique(oceanus_contributions$from)\n\n# Step 5: Get 1-hop neighborhood edges\noceanus_ego_edges <- edges_tbl_clean %>%\n  filter(from %in% oceanus_artist_indices | to %in% oceanus_artist_indices)\n\n# Step 6: Get involved node indices\noceanus_ego_node_indices <- unique(c(oceanus_ego_edges$from, oceanus_ego_edges$to))\n\n# Step 7: Keep only Person and Album nodes\nincluded_types <- c(\"Person\", \"Album\")\noceanus_ego_nodes <- nodes_tbl_clean[oceanus_ego_node_indices, ] %>%\n  filter(node_type %in% included_types)\n\n# Step 8: Remap indices for visNetwork\nindex_lookup <- tibble(\n  old_index = oceanus_ego_node_indices,\n  new_index = 1:length(oceanus_ego_node_indices)\n)\n\n# Step 9: Reindex edges\noceanus_ego_edges_vis <- oceanus_ego_edges %>%\n  left_join(index_lookup, by = c(\"from\" = \"old_index\")) %>%\n  rename(from_new = new_index) %>%\n  left_join(index_lookup, by = c(\"to\" = \"old_index\")) %>%\n  rename(to_new = new_index) %>%\n  filter(!is.na(from_new) & !is.na(to_new)) %>%\n  transmute(from = from_new, to = to_new, label = edge_type)\n\n# Step 10: Prepare nodes for visNetwork\noceanus_ego_nodes_vis <- oceanus_ego_nodes %>%\n  mutate(id = 1:n(),\n         label = name,\n         group = node_type,\n         title = paste0(\"<b>\", name, \"</b><br>Type: \", node_type)) %>%\n  select(id, label, group, title)\n\n# Step 11: Draw interactive network\nvisNetwork(oceanus_ego_nodes_vis, oceanus_ego_edges_vis, height = \"700px\", width = \"100%\") %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%\n  visInteraction(navigationButtons = TRUE) %>%\n  visLayout(randomSeed = 42) %>%\n  visLegend(useGroups = TRUE, position = \"right\", main = \"Node Types\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-15-1.png)\n:::\n:::\n\n\n\n# 5. Visualize the careers of three artists. Compare and contrast their rise in popularity and influence.\n\nThis section explores and compares the careers of three selected artists—***Sailor Shift, Beatrice Albright, and Daniel O'Connell***—using multiple visualizations. It analyzes their contributions to songs and albums, highlights key metrics like total works, notable songs, Oceanus Folk involvement, and collaborations, and visualizes their timelines and ego networks. Together, these insights reveal differences in artistic output, genre focus, and influence patterns, helping to understand each artist’s trajectory and role in shaping the Oceanus Folk genre.\n\n## 5.1. Identify the three Artists\n\nThis step defines the three focal artists—***Sailor Shift, Beatrice Albright, and Daniel O'Connell***—whose careers will be analyzed and compared in terms of influence, productivity, and genre involvement.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_artists <- c(\"Sailor Shift\", \"Beatrice Albright\", \"Daniel O'Connell\")\n```\n:::\n\n\n\n## 5.2. Get Person IDs\n\nThis step retrieves the unique IDs of the selected artists from the cleaned nodes table, allowing their contributions and relationships to be accurately tracked in the network.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nartist_nodes <- nodes_tbl_clean %>%\n  filter(name %in% selected_artists, node_type == \"Person\") %>%\n  select(artist_name = name, artist_id = id)\n```\n:::\n\n\n\n## 5.3. Getting their Contributions (Songs/Albums)\n\nThis step compiles all songs and albums contributed to by the selected artists by linking their IDs to relevant edges in the graph (e.g., `ComposerOf`, `PerformerOf`, `ProducerOf`, `LyricistOf`). It joins these connections with metadata such as release date, genre, and notability, producing a detailed table of each artist's creative works. This forms the foundation for comparing their productivity, genre focus, and the recognition they’ve received across their careers.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Map artist IDs to tidygraph node index\nartist_nodes_indexed <- artist_nodes %>%\n  left_join(id_map, by = c(\"artist_id\" = \"id\")) %>%\n  rename(index = index)\n\n# Step 2: Filter contribution edges\ncontrib_edges <- edges_tbl_clean %>%\n  filter(edge_type %in% c(\"ComposerOf\", \"PerformerOf\", \"ProducerOf\", \"LyricistOf\"))\n\n# Step 3: Join with artist names using index\nartist_contribs <- contrib_edges %>%\n  left_join(artist_nodes_indexed, by = c(\"from\" = \"index\")) %>%\n  filter(!is.na(artist_name))  # Only keep selected artists\n\n# Step 4: Join with work details\nartist_works <- artist_contribs %>%\n  left_join(nodes_tbl_clean, by = c(\"to\" = \"id\")) %>%\n  rename(work_name = name, work_type = node_type) %>%\n  select(artist_name, work_name, release_date, genre, notable, work_type)\n\n# Showing the artist_work\ndatatable(\n  artist_works,\n  rownames = FALSE,\n  options = list(\n    pageLength = 10,\n    autoWidth = TRUE,\n    scrollX = TRUE\n  ),\n  caption = htmltools::tags$caption(\n    style = 'caption-side: top; text-align: left; font-size: 16px; font-weight: bold;',\n    'Table: ', 'Works Contributed by Selected Artists'\n  )\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-18-1.png)\n:::\n:::\n\n\n\n## 5.4. Bar Chart of Key Metrics\n\nThis bar chart compares four key metrics—***total works, notable works, Oceanus Folk works,** and **collaborations***—for the three selected artists.\n\n***Sailor Shift*** stands out significantly, with the highest values across all categories, especially in Oceanus Folk contributions (45) and notable works (34), reflecting her central role in popularizing the genre. In contrast, ***Beatrice Albright and Daniel O’Connell*** show similar and more modest activity levels, each with 11 total works and notable works, and limited collaborations (1 each).\n\nThis visualization clearly highlights Sailor’s greater productivity, genre influence, and broader reach in the music industry.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrising_star_profile %>%\n  filter(name %in% selected_artists) %>%\n  pivot_longer(\n    cols = c(total_works, notable_works, oceanus_folk_works, collaborations),\n    names_to = \"metric\",\n    values_to = \"value\"\n  ) %>%\n  ggplot(aes(x = name, y = value, fill = name)) +\n  geom_col(position = position_dodge(width = 0.9)) +\n  geom_text(\n    aes(label = value),\n    position = position_dodge(width = 0.9),\n    vjust = -0.5,\n    size = 3.5\n  ) +\n  facet_wrap(~metric, scales = \"free_y\") +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) + \n  labs(\n    title = \"Comparison of Artist Metrics\",\n    y = \"Count\",\n    x = \"Artist\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1)\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-19-1.png)\n:::\n:::\n\n\n\n## 5.4. Plotting Career Timeline\n\nThis timeline chart visualizes the release dates of works by the three selected artists, focusing on the top genres they contributed to. Each point represents a song or album, with shapes indicating genre and colors showing whether the work is notable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_genres <- artist_works %>%\n  count(genre, sort = TRUE) %>%\n  slice_head(n = 6) %>%\n  pull(genre)\n\nartist_subset <- artist_works %>%\n  filter(genre %in% top_genres)\n\nggplot(artist_subset, aes(x = release_date, y = artist_name, shape = genre, color = notable)) +\n  geom_jitter(width = 0.3, height = 0.3, size = 3, alpha = 0.7) +\n  scale_color_manual(values = c(`TRUE` = \"#a1d99b\", `FALSE` = \"#fcbba1\")) +\n  labs(title = \"Timelines (Top Genres)\", shape = \"Genre\", color = \"Notable\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-20-1.png)\n:::\n:::\n\n\n\n::: callout-tip\n### Insights\n\n-   Sailor Shift has the longest and most consistent timeline, with steady output across genres, especially Oceanus Folk.\n-   Daniel O’Connell and Beatrice Albright are active mainly between 2028–2036, with fewer works and less genre diversity.\n-   Most of Beatrice’s and Daniel’s works are notable, suggesting quality over quantity.\n-   Sailor’s mix of notable and non-notable works shows broad experimentation and prolific output.\n:::\n\n## 5.5. Plotting EGO Network Diagram for Top 3 Artists\n\nThis interactive ego network visualizes the immediate (1-hop) relationships of the three selected artists—***Sailor Shift, Beatrice Albright, and Daniel O'Connell*****.** It maps their direct connections to other people, songs, albums, groups, and record labels using `visNetwork`, with nodes colored by type and edges labeled by relationship.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nego_artist_nodes <- nodes_tbl_clean %>%\n  filter(name %in% selected_artists, node_type == \"Person\") %>%\n  left_join(id_map, by = c(\"id\" = \"id\")) %>%\n  select(artist_name = name, artist_id = id, index)\n\nego_indices <- ego_artist_nodes$index  \n\n# 3. Extract ego subgraph (1-hop neighborhood)\nego_subgraph <- graph %>%\n  activate(nodes) %>%\n  filter(node_is_adjacent(ego_indices) | row_number() %in% ego_indices)\n\n# 4. Prepare node data\nnodes_data <- ego_subgraph %>%\n  activate(nodes) %>%\n  as_tibble() %>%\n  mutate(id = row_number(),\n         label = name,\n         group = node_type,\n         title = paste0(\"<b>\", name, \"</b><br>Type: \", node_type)) %>%\n  select(id, label, group, title)\n\n# 5. Prepare edge data\nedges_data <- ego_subgraph %>%\n  activate(edges) %>%\n  as_tibble() %>%\n  mutate(from = as.integer(from),\n         to = as.integer(to),\n         label = edge_type) %>%\n  select(from, to, label)\n\n# 6. Visualize in visNetwork\nvisNetwork(nodes_data, edges_data, height = \"600px\", width = \"100%\") %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%\n  visInteraction(navigationButtons = TRUE) %>%\n  visLayout(randomSeed = 42) %>%\n  visLegend(\n    useGroups = TRUE,              \n    position = \"right\",           \n    main = \"Node Types\"           \n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-21-1.png)\n:::\n:::\n\n\n\n::: callout-tip\n### Insights\n\n-   ***Sailor Shift*** is at the center of a dense cluster, showing her extensive influence and involvement in various musical roles.\n-   ***Beatrice Albright and Daniel O’Connell*** appear in smaller clusters, reflecting fewer collaborations and a narrower scope.\n-   The visualization reveals shared connections (e.g., Ivy Echoes) and highlights how Sailor’s network spans more genres and institutions.\n:::\n\n# 6. Predicting the next Oceanus Folk stars over the next five year\n\nThis section identifies promising new artists who are likely to become the next Oceanus Folk stars. Using the rising star profiles, it filters for individuals with a strong commitment to the genre, a notable body of work, and a relatively recent or rapid rise in visibility. By applying data-driven thresholds and ranking by impact (e.g., notable works, collaborations), the analysis highlights top candidates who exhibit the traits of future genre leaders. These predictions help spotlight emerging talent shaping the next wave of Oceanus Folk music.\n\n## 6.1. Understanding Profiles of Current Stars\n\nThis step reviews the profile metrics of the three selected artists to establish a benchmark for identifying future stars, focusing on their total works, notable songs, Oceanus Folk contributions, and collaborations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrising_star_profile %>%\n  filter(name %in% selected_artists)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 10\n  person_id name      total_works notable_works oceanus_folk_works first_release\n      <int> <chr>           <int>         <int>              <int>         <int>\n1     17255 Sailor S…          47            34                 45          2024\n2     17349 Beatrice…          11            11                 11          2031\n3     17355 Daniel O…          11            11                 11          2031\n# ℹ 4 more variables: first_notable <int>, time_to_notability <int>,\n#   from <int>, collaborations <int>\n```\n\n\n:::\n:::\n\n\n\n## 6.2. Defining Thresholds to Filter Candidates\n\nThis step applies a set of criteria to identify emerging Oceanus Folk artists with high potential. The filters select artists with at least 5 Oceanus Folk works, 6 or more notable works, a debut within the past 20 years, and either a rapid rise to notability or recent entry. The resulting candidates—***Zacharie Martins, Orla Seabloom, Tao Jin, and Lei Jin***—demonstrate strong genre commitment and early success, positioning them as likely future stars.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the current year\ncurrent_year <- 2025\n\n# Find promising Oceanus Folk artists\nfuture_stars <- rising_star_profile %>%\n  filter(\n    oceanus_folk_works >= 5,                          # commitment to genre\n    notable_works >= 6,                               # some level of recognition\n    !name %in% selected_artists,                      # exclude current stars\n    first_release >= (current_year - 20),              # relatively new\n    time_to_notability <= 3 | is.na(time_to_notability)  # fast risers or too new\n  ) %>%\n  arrange(desc(notable_works), desc(collaborations))  # sort by impact\n\n# Preview top candidates\nfuture_stars %>% select(name, total_works, notable_works, oceanus_folk_works, collaborations, time_to_notability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  name             total_works notable_works oceanus_folk_works collaborations\n  <chr>                  <int>         <int>              <int>          <int>\n1 Zacharie Martins          13            13                  7              0\n2 Orla Seabloom              9             9                  9              2\n3 Tao Jin                    8             8                  5              0\n4 Lei Jin                    7             6                  5              0\n# ℹ 1 more variable: time_to_notability <int>\n```\n\n\n:::\n:::\n\n\n\n## 6.3. Pick Top 3 Candidates and Justify\n\nThis step selects the top 3 rising Oceanus Folk artists based on a combined score of notable works, collaborations, and genre contributions. The selected artists—***Zacharie Martins, Orla Seabloom, and Tao Jin***—stand out for their strong early recognition and dedication to Oceanus Folk. Orla’s higher collaboration count suggests strong network potential, while Zacharie and Tao show consistent output and fast-rising impact, making them strong candidates for future stardom.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Choose the top 3 candidates\ntop_3_future_stars <- future_stars %>% \n  slice_max(order_by = notable_works + collaborations + oceanus_folk_works, n = 3)\n\ntop_3_future_stars\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 10\n  person_id name      total_works notable_works oceanus_folk_works first_release\n      <int> <chr>           <int>         <int>              <int>         <int>\n1      3504 Zacharie…          13            13                  7          2007\n2     17340 Orla Sea…           9             9                  9          2029\n3      5459 Tao Jin             8             8                  5          2010\n# ℹ 4 more variables: first_notable <int>, time_to_notability <int>,\n#   from <int>, collaborations <int>\n```\n\n\n:::\n:::\n\n\n\n## 6.4. Radar Chart for Each Candidates\n\nThis radar chart visually compares the top three future Oceanus Folk stars—***Zacharie Martins, Orla Seabloom, and Tao Jin***—across five key dimensions: total works, notable works, Oceanus Folk contributions, collaborations, and rapid rise (time to notability). Each chart normalizes scores to a 0–100 scale, helping highlight each artist’s relative strengths.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradar_data <- top_3_future_stars %>%\n  select(total_works, notable_works, oceanus_folk_works, collaborations, time_to_notability) %>%\n  as.data.frame()\n\n# Set row names to artist names\nrownames(radar_data) <- top_3_future_stars$name\n\n# Rename columns for better display\ncolnames(radar_data) <- c(\"Total\", \"Notable\", \"Oceanus\\nFolk\", \"Collabs\", \"Rapid\\nRise\")\n\n# Invert Time to Notability (BEFORE scaling)\nradar_data[, \"Rapid\\nRise\"] <- max(radar_data[, \"Rapid\\nRise\"], na.rm = TRUE) - \n                               radar_data[, \"Rapid\\nRise\"]\n\n# Normalize all features to 0-100 range\nradar_data_scaled <- as.data.frame(lapply(radar_data, function(x) {\n  scales::rescale(x, to = c(0, 100))\n}))\nrownames(radar_data_scaled) <- rownames(radar_data)\n\n# Set layout with better margins\npar(mfrow = c(1, 3), \n    mar = c(2, 2, 4, 2),\n    oma = c(1, 1, 3, 1),\n    family = \"sans\")\n\n# Loop and plot\nfor (i in 1:nrow(radar_data_scaled)) {\n  artist_name <- rownames(radar_data_scaled)[i]\n  artist_values <- radar_data_scaled[i, , drop = FALSE]\n  \n  radar_individual <- rbind(\n    rep(100, ncol(radar_data_scaled)),\n    rep(0, ncol(radar_data_scaled)),\n    artist_values\n  )\n  \n  radarchart(radar_individual,\n             axistype = 1,\n             pcol = \"darkorange\",\n             pfcol = rgb(1, 0.5, 0, 0.3),\n             plwd = 2,\n             cglcol = \"gray\",\n             cglty = 1,\n             cglwd = 0.8,\n             axislabcol = \"darkblue\",\n             caxislabels = paste0(seq(0, 100, 25), \"%\"),\n             vlcex = 0.85,\n             title = artist_name,\n             calcex = 0.8,\n             cex.main = 1.2)\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-25-1.png)\n:::\n:::\n\n\n\n# 7. Conclusion\n\nThis study of the VAST Challenge 2025 Mini-Challenge 1 provides a rich, network-based exploration of how Sailor Shift catalyzed the global rise of Oceanus Folk. Through data wrangling, exploratory analysis, and graph-based modeling, we unpacked her influence, visualized genre growth, and forecasted future talent.\n\n::: callout-tip\n## Key Insights\n\n-   Sailor Shift leads in all metrics: total works, notable songs, Oceanus Folk contributions, and collaborations.\n-   Her ego network shows wide influence across people, albums, and genres.\n-   Oceanus Folk grew significantly post-2028, aligning with her rise.\n:::\n\n::: callout-note\n## Career Comparison\n\n-   Beatrice Albright and Daniel O’Connell had steady but smaller careers.\n-   Visuals showed Sailor’s sustained, diverse output and broader influence.\n:::\n\n::: callout-tip\n## Future Stars Identified\n\n-   Using artist profiles, we selected Zacharie Martins, Orla Seabloom, and Tao Jin as the next potential Oceanus Folk stars.\n\n-   Radar charts highlighted:\n\n    -   Zacharie for volume and impact,\n    -   Orla for collaborations and genre depth,\n    -   Tao for rapid recognition.\n:::\n\n::: callout-note\n## Key Takeaways\n\n-   Network and profile analytics effectively track artistic influence.\n-   This approach helps forecast rising talent in niche genres like Oceanus Folk.\n:::\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}